[package]
name = "kvdb-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kvdb-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "10.0.0"
kvdb-core = { path = "../kvdb-core" }
